### ISSUE TITLE
Be able to distinguish if order has same address as store

### ISSUE THREAD

**Issue by gcandal** [hivesolutions/budy#21]
## Description

Be able to easily distinguish, via a model attribute, if an order has the same address as the store it is associated with. In practice, this means knowing if [set_store_shipping](https://github.com/hivesolutions/budy/blob/master/src/budy/controllers/api/order.py#L281) or similar methods were called in that order.

Note: I also think it would be useful if this new attribute/flag could be in list_names.

### Why

It is useful for easily making decisions that depend on the order being shipped (or billed) to the store or not.

### Current solution

Compare order.shipping_address with order.store.address attributes one by one.

**Comment by joamag** [comment]
This is not an ideal solution, please keep in mind that the store may change address in the middle of the process breaking the logic.

You should use some kind of [meta attribute](https://github.com/hivesolutions/appier_extras/blob/master/src/appier_extras/parts/admin/models/base.py#L96) in the order to mark it for such condition.

I'll try to find a better solution for this situation.

**Comment by gcandal** [comment]
That makes sense, but I guess using the meta attribute has the same consistency problem.

What if we added a model method where we'd compare the fields that constitute a fully identifiable address? Something like:

```python
def ship_store(self):
    return self.shipping_address.address == self.store.address.address
      and self.shipping_address.postal_code == self.store.address.postal_code
      and (...)
```

Consistency would be achieved at all times and it simplifies client code.

**Comment by joamag** [comment]
Using e80d1f2b0a40d49d5bf89b3e5052b3f2cde98b95 you can set a meta attribute on the Order eg: `ship_to_store = 1` and then use it later to make decisions on a certain order.
